modLoader="javafml" 

loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]] 

modId="illagerrevolutionmod"
version="${mod_version}}"
displayName="${mod_name}"
logoFile="illagerrevolution.png"
authors="${mod_authors}"
description='''${mod_description}'''


[[dependencies.illagerrevolutionmod]]
    
    modId="forge" 
    mandatory=true 
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.illagerrevolutionmod]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
